image: docker:latest

services:
  - docker:dind
  - mysql:latest

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: docker,localstorage
  MYSQL_ROOT_PASSWORD: admin
  MYSQL_DATABASE: belajar
  MYSQL_USER: belajar
  MYSQL_PASSWORD: java

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: mvn package -B
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
    - echo "$GCLOUD_CREDENTIAL" > gcloud-credential.json
    - docker build -t $CI_PROJECT_PATH:$CI_COMMIT_SHA .
    - docker tag $CI_PROJECT_PATH:$CI_COMMIT_SHA $CI_PROJECT_PATH:latest
    - docker login -u endymuhardin -p $DOCKERHUB_PASSWORD
    - docker push $CI_PROJECT_PATH
    - docker logout
    - rm gcloud-credential.json

k8s-deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
  - echo "$GCLOUD_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - gcloud config set compute/zone asia-east1-a
  - gcloud config set project belajar-ci
  - gcloud config set container/use_client_certificate True
  - gcloud container clusters get-credentials belajar-ci
  - kubectl apply -f k8s
  - kubectl set image deploy/belajar-ci-app belajar-ci=endymuhardin/belajar-ci:latest
  - rm key.json
