version: "2.1"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=belajar
      - MYSQL_USER=belajar
      - MYSQL_PASSWORD=java

  belajarci-app:
    image: endymuhardin/belajar-ci
    depends_on:
      - mysql
    ports:
      - 80:8080