# gcloud compute disks create --size=10GB --zone=asia-east1-a belajar-ci-pv-1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: belajar-ci-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: belajar-ci-pv-1
    fsType: ext4